//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.products = new HashSet<product>();
        }
    
        public int category_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public string category1 { get; set; }
        public string ImageFilePath { get; set; }
    
        public virtual Product_Location Product_Location { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
