//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint_Type
    {
        public Complaint_Type()
        {
            this.Customer_Complaints = new HashSet<Customer_Complaints>();
        }
    
        public int Complaint_Type_Id { get; set; }
        public string Complaint_Tpe { get; set; }
    
        public virtual ICollection<Customer_Complaints> Customer_Complaints { get; set; }
    }
}
