//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Referals
    {
        public int CR_Id { get; set; }
        public int Customer_Id { get; set; }
        public string referees_Email { get; set; }
        public string Joining_Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
