//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_boy
    {
        public Delivery_boy()
        {
            this.OrderToDelivers = new HashSet<OrderToDeliver>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<OrderToDeliver> OrderToDelivers { get; set; }
    }
}
