//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GroceryShopModels : DbContext
    {
        public GroceryShopModels()
            : base("name=GroceryStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<about> abouts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Complaint_Type> Complaint_Type { get; set; }
        public DbSet<Customer_Referals> Customer_Referals { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DealAndDiscount> DealAndDiscounts { get; set; }
        public DbSet<Delivery_boy> Delivery_boy { get; set; }
        public DbSet<List> Lists { get; set; }
        public DbSet<orderProductsPrior> orderProductsPriors { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<OurSatisfiedCustomer> OurSatisfiedCustomers { get; set; }
        public DbSet<OurTeam> OurTeams { get; set; }
        public DbSet<Product_Location> Product_Location { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<Review_Ratings> Review_Ratings { get; set; }
        public DbSet<SKU> SKUs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Customer_Complaints> Customer_Complaints { get; set; }
        public DbSet<orderProductsTrain> orderProductsTrains { get; set; }
        public DbSet<OrderToDeliver> OrderToDelivers { get; set; }
    }
}
