//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderToDeliver
    {
        public int OrderID { get; set; }
        public int DeliveryManId { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Delivery_boy Delivery_boy { get; set; }
        public virtual order order { get; set; }
    }
}
