
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroceryStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductCategory
{

    public string category { get; set; }

    public int product_id { get; set; }

    public string ImageFilePath { get; set; }

    public int category_id { get; set; }

    public decimal SellingPrice { get; set; }

    public decimal DiscountPrice { get; set; }

    public string product_name { get; set; }

    public decimal CostPrice { get; set; }

    public string FullDescription { get; set; }

    public string MartLocation { get; set; }

    public string ImageFilePath2 { get; set; }

}

}
