//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU
    {
        public SKU()
        {
            this.products = new HashSet<product>();
        }
    
        public int SkuId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
