//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {


        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.OurTeams = new HashSet<OurTeam>();
        }

        public int UserID { get; set; }

        [DisplayName("Full Name")]
        [Required(ErrorMessage ="This is Reqired Field")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "This is Reqired Field")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This is Reqired Field")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "This is Reqired Field")]
        public string Password { get; set; }

        [DisplayName("Confirm Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        public string ContactNo { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Subscription { get; set; }
        public string Home_Address { get; set; }
        public string Office_Addres { get; set; }
        public string Other_Address { get; set; }
        public string LoginErrorMsg { get; set; }

        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Delivery_boy Delivery_boy { get; set; }
        public virtual ICollection<OurTeam> OurTeams { get; set; }
    }
}
