//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Customer_Complaints = new HashSet<Customer_Complaints>();
            this.Customers = new HashSet<Customer>();
            this.OurTeams = new HashSet<OurTeam>();
            this.ProductNotifications = new HashSet<ProductNotification>();
        }

        public int UserID { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "This is Reqired Field")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This is Reqired Field")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This Field is Required")]
        public string Password { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [DisplayName("Confirm Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        public string LoginErrorMsg { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        public string ContactNo { get; set; }
        public Nullable<bool> Subscription { get; set; }
        public string Home_Address { get; set; }
        public string Office_Addres { get; set; }
        public string Other_Address { get; set; }
        public Nullable<int> Role { get; set; }
        public string code { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Complaints> Customer_Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Delivery_boy Delivery_boy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OurTeam> OurTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductNotification> ProductNotifications { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
